@echo off
rem Build script for TeX Live: all outputs go to auxil, then PDF is moved back
if not exist auxil mkdir auxil
if not exist out mkdir out
echo Running pdflatex (1/4) -> auxil...
pdflatex -interaction=nonstopmode -file-line-error -output-directory=auxil hsmw-vorlage.tex
echo Running biber (2/4)...
biber hsmw-vorlage
echo Running makeindex for nomenclature (3/4)...
makeindex auxil\hsmw-vorlage.nlo -s nomencl.ist -o auxil\hsmw-vorlage.nls
echo Running pdflatex (4/4) -> auxil...
pdflatex -interaction=nonstopmode -file-line-error -output-directory=auxil hsmw-vorlage.tex
pdflatex -interaction=nonstopmode -file-line-error -output-directory=auxil hsmw-vorlage.tex
echo Moving PDF to out directory...
move /Y auxil\\hsmw-vorlage.pdf out\\hsmw-vorlage.pdf
echo Build finished. PDF moved to out\\hsmw-vorlage.pdf
