This is makeindex, version 2.16 [MiKTeX 25.12].
Scanning style file C:/Users/inorpoth/OneDrive - ALTEN Group/Dokumente/Masterarbeit/out/hsmw-vorlage-rw.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file hsmw-vorlage-rw.acn....done (3 entries accepted, 0 rejected).
Sorting entries....done (5 comparisons).
Generating output file hsmw-vorlage-rw.acr....done (12 lines written, 0 warnings).
Output written in hsmw-vorlage-rw.acr.
Transcript written in hsmw-vorlage-rw.alg.
